# Generated by Django 3.2.23 on 2023-12-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='orderditems',
        ),
    ]
