# Generated by Django 3.2.23 on 2023-12-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_shippingaddress_orderditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
